#!/bin/bash

# Constants
META_PATH="META-INF"
EDIFY_PATH="$META_PATH/com/google/android"
SETUP_SCRIPT="zippo-setup.sh"

SCRIPT_DEST="$EDIFY_PATH/updater-script"
INCLUDE_FILES="$META_PATH LICENSE README.md"


# Functions
function generate-zip {
  ZIP_NAME="${1%.*}.zip"
  FILES="$INCLUDE_FILES $@"

  zip -r "$ZIP_NAME" $FILES
}

function tidy-up {
  rm "$SCRIPT_DEST"
}


# Main
for d in */ ; do
  # Skip META-INF path
  [[ "$d" == "$META_PATH/" ]] && continue

  TARGET="${d%/}"
  echo "~ Forging ${TARGET}.zip..."

  # Run specific ZIP setup script
  [[ -x "$TARGET/$SETUP_SCRIPT" ]] && ( cd "$TARGET/" && "./$SETUP_SCRIPT" )

  # Place updater-script
  cp -f "$TARGET/updater-script" "$SCRIPT_DEST"

  # Generate final ZIP
  generate-zip "$TARGET"
done

tidy-up
